---
- name: Install MySQL and Redis
  hosts: database_servers
  become: yes
  tasks:
    - name: Update Package Cache
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install Redis Server
      apt:
        name: redis-server
        state: present

    - name: Get MySQL Server Version
      command: mysql -V
      register: mysql_version_output
      changed_when: false

    - name: Get Redis Server Version
      command: redis-server --version
      register: redis_version_output
      changed_when: false

    - name: Display Results
      debug:
        var: "{{ item }}"
      with_items:
        - mysql_version_output.stdout
        - redis_version_output.stdout
