---
- name: Install MySQL and Redis
  hosts: database_servers
  become: yes
  tasks:
    - name: Install MySQL Server (Amazon Linux)
      yum:
        name: mysql-server
        state: present
      when: os_distribution.stdout == 'amzn'
      register: mysql_install_output

    - name: Get MySQL Server Version
      command: mysql -v
      register: mysql_version_output
      changed_when: false
      when: os_distribution.stdout == 'amzn'

    - name: Install Redis Server (Amazon Linux)
      yum:
        name: redis
        state: present
      when: os_distribution.stdout == 'amzn'
      register: redis_install_output

    - name: Get Redis Server Version
      command: redis-server --version
      register: redis_version_output
      changed_when: false
      when: os_distribution.stdout == 'amzn'

    - name: Display Results
      debug:
        var: "{{ item }}"
      with_items:
        - mysql_install_output
        - mysql_version_output
        - redis_install_output
        - redis_version_output
